---
# tasks file for rds
- name: Create mysql on RDS in a VPC
  rds:
    command: create
    instance_name: ansible-rds
    region: "{{ region }}"
    size: "{{ size }}"
    instance_type: "{{ instance_type }}"
    db_engine: "{{ db_engine }}"
    engine_version: "{{ engine_version }}"
    #Use default (latest) DB engine (e.g., 9.3.x)
    #engine_version: "{{ engine_version }}"
    subnet: "{{ subnet }}"
    #Use default db parameter group
    #parameter_group: "{{ parameter_group }}"
    multi_zone: no
    port: 3306
    db_name: "{{ db_name }}"
    username: "{{ username }}"
    password: "{{ password }}"
    vpc_security_groups: "{{ security_groups }}"
    #iops: "{{ iops }}"
    #maint_window: "{{ maint_window }}"
    #backup_window: "{{ backup_window }}"
    backup_retention: 0
    #zone: "{{ zone }}"
    tags:
      Environment: testing
      Application: ansible
      register: rds
- name: Debug RDS facts
  rds:
    command: facts
    instance_name: ansible-rds
    region: "{{ region }}"
  register: rds_facts
  until: not(rds_facts.instance.endpoint is none)
  retries: 20
  delay: 30
- debug: var=rds_facts
