---
- hosts: others
  become: yes
  tasks:
  - name: install tree in RedHat
    yum:
      name: "{{webserver_package}}"
      state: present
    when: ansible_os_family == "RedHat"
  - debug: 
      msg: "{{webserver_package}}"
  - name: install tree in Ubuntu
    apt:
      name: "{{ webserver_package }}"
      state: present
    when: ansible_os_family == "Debian"
  - debug:
      msg: "{{ webserver_package }}"
