---
- hosts: all
  become: yes
  tasks:
  - name: copy the file
    copy:
      src: /home/jenkins/apache.sh
      dest: /home/ec2-user/apache.sh
      owner: ec2-user
      group: ec2-user
      mode: u=rwx,g=rwx,o=r
  - name: run the below command
    shell: ./home/ec2-user/apache.sh
  - name: restart the apache service
    shell: sudo service httpd restart
