--- 
files: 
  - 
    destination: /var/www/
    source: /
hooks: 
  ApplicationStart: 
    - 
      location: scripts/start_server.sh
      runas: root
      timeout: 300
  ApplicationStop: 
    - 
      location: scripts/stop_server.sh
      runas: root
      timeout: 300
  BeforeInstall: 
    - 
      location: scripts/install_dependencies.sh
      runas: root
      timeout: 300
os: linux
version: 0.0

