---
version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/ansible-jaya
hooks:
  BeforeInstall:
    - location: .scripts/apache.sh
      timeout: 300
      runas: root
#  AfterInstall:
#    - location: scripts/change_permissions.sh
#      timeout: 300
#      runas: root
  ApplicationStart:
    - location: .scripts/apache_start.sh
      timeout: 300
      runas: root
### https://github.com/abel30567/AWS_CodeDeploy_Example
### https://www.youtube.com/watch?v=F6oLG-LyIhc
