---
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: ./home/ec2-user/apache.sh
      timeout: 300
      runas: root
#  AfterInstall:
#    - location: scripts/change_permissions.sh
#      timeout: 300
#      runas: root
  ApplicationStart:
    - location: ./home/ec2-user/apache_start.sh
      timeout: 300
      runas: root
### https://github.com/abel30567/AWS_CodeDeploy_Example
### https://www.youtube.com/watch?v=F6oLG-LyIhc
