---
- hosts: others
  become: yes
 # gather_facts: no
  tasks:
  - name: install "{{item}}" in RedHat
    yum:
      name: "{{item}}"
      state: present
    with_items:
    - git
    - httpd
    - tree
    - wget
    when: ansible_os_family == "RedHat"
  - name: install "{{item}}" in ubuntu
    apt:
      name: "{{item}}"
      state: present
    with_items:
    - apache2
    - tree
    when: ansible_os_family == "Debian"
