---
- hosts: others
  become: yes
  #gather_facts: no
  tasks:
  - name: ping all
    ping:
  - name: install tree
    yum:
      name: tree
      #state: absent
   # debug:
   #   msg: "{{ webserver_package }}"
    when: ansible_os_family == "RedHat"
  - name: install tree
    apt:
      name: tree
      #state: absent
   # debug:
   #   msg: "{{ webserver_package }}"
    when: ansible_os_family == "Debian"

